name: Build and Zip Blender Addon

on:
  push:
    branches:
      - Experimental
  pull_request:
    branches:
      - Experimental

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install required packages
      run: |
        python -m pip install --upgrade pip

    - name: Zip Blender Addon
      run: |
        mkdir -p output
        zip -r output/Mcblend.zip Mcblend Source

    - name: Upload ZIP as artifact
      uses: actions/upload-artifact@v2
      with:
        name: Mcblend Experimental Build
        path: output/Mcblend.zip
